spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/spring_batch?useUnicode=true?characterEncoding=UTF-8?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  batch:
    initialize-schema: always
app:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/app?useUnicode=true?characterEncoding=UTF-8?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  batch:
    initialize-schema: always